### ISSUE TITLE
numpy / ep2 и ep3 : ввод

### ISSUE THREAD

**Issue by avasyukov** [NikolayMorgunov/np-lab#1]
Не баг. Но очень тянется рука навести красоту вот здесь:
https://github.com/NikolayMorgunov/np-lab/blob/7d920c6018c220c87f02a07ce94d947024a09874/ep2.py#L7-L12

Считать `sig` можно одной строчкой "родными" методами numpy, получив сразу numpy-ный array. Заполнить `x` можно сразу `np.arange`.

Upd: и аналогично вот здесь:
https://github.com/NikolayMorgunov/np-lab/blob/7d920c6018c220c87f02a07ce94d947024a09874/ep3.py#L22-L26

**Comment by NikolayMorgunov** [comment]
Спасибо, исправил
